//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3Test_2.Data
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class FileDBC
    {
        public int id { get; set; }
        public string ProfilePic { get; set; }
        public string Qualification { get; set; }
        public string Email { get; set; }
        public string Uid { get; set; }
        public string cn { get; set; }
        public string sn { get; set; }
        public string ctn { get; set; }
    }
}
